### ISSUE TITLE
[Bug] Switching from deposit tab to withdraw keeps previous tab input amount

### ISSUE THREAD

**Issue by umamianon** [Arbi-s/umami-v2#18]
Can be an issue where the value is higher than their max, should be defaulted to 0 on tab switch.

**Comment by 0xdapper** [comment]
I think the issue is we are sharing the input field between both. Maybe we need to introduce 2 state variables to track the input on both the tabs? Would need to add onChange and value props to current `FormField` I think? https://github.com/Arbi-s/umami-v2/blob/501e2aecfbac621b91b1240a36c7f3e7478fe438/src/components/VaultTransactionCard.tsx#L42-L49

Thoughts @0xburden?

**Comment by 0xburden** [comment]
@0xdapper that would disrupt the way that Formik handles form state, i have a fix that will solve issue will commit shortly
